### ISSUE TITLE
Sampling bias in year-to-year drift rates

### ISSUE THREAD

**Issue by trvrb** [trvrb/flux#22]
> The authors do not seem to discuss this a problematic aspect of their results relating inferred drift to influenza disease incidence -- namely that biased sampling of clades, in each season, could cause the observed correlations. If clades were sampled for HI assays unequally in each season, as I suspect, then this fact alone might cause the trend towards apparently more drift in the clade that was sampled most intensively in each season (and to which most ILI was attributed). This is an obvious possible confound for the analysis presented in Fig. 4, and it should be ruled out by simulation of constant true rates of antigenic drift, varible sampling proportions in each season, and reconstructed drift using BMDS.

**Comment by lixingguang** [comment]
This is no response.
