### ISSUE TITLE
Sampling bias in incidence correlation

### ISSUE THREAD

**Issue by trvrb** [trvrb/flux#23]
> Likewise, in Fig. 5, the negative correlation between drift in different clades in each season could, again, be driven by variation in the number of strains per clade that were subjected to HI each season. The authors could rule this out either by simulation or, more simply, be repeating their analysis after subsampling an equal number of isolates per clade each season for inclusion into the BMDS.

**Comment by lixingguang** [comment]
And this is  also no response.
